apiVersion: apps/v1
kind: Deployment
metadata:
  name:  modhu-hub
  namespace: demo
spec:
  selector:
    matchLabels:
      app: modhu-hub
  template:
    metadata:
      labels:
        app: modhu-hub
    spec:
      containers:
        - name: modhu-hub
          image: faisal404/modhu-hub:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000